import { ArrowRight, ArrowUpRight, BadgeCheck, Network } from 'lucide-react';
import { organisers } from '../data/site';
import { Accordion, SectionTitle } from './ui';

export function AboutSection() {
  return <><section id="about" className="mx-auto max-w-[1100px] px-6 py-20 md:py-28"><SectionTitle label="About UNFOLD 2026" title={<>From campus project to <em className="font-display italic">venture.</em></>} text="UNFOLD is a focused 48-hour transition from academic project to a venture-ready startup. Build clarity around your problem, validate it with mentors, and leave with a stronger story for what comes next." /><div className="grid gap-4 md:grid-cols-2">{organisers.map(({ Icon, name, detail, tag }, index) => <article key={name} className="group relative overflow-hidden rounded-3xl border border-stroke bg-surface p-7 transition hover:-translate-y-1 hover:border-[#89AACC]/60"><span className="absolute right-6 top-5 text-[10px] uppercase tracking-[.16em] text-muted">0{index + 1}</span><div className="mb-8 grid h-12 w-12 place-items-center rounded-2xl border border-[#89AACC]/30 bg-[#89AACC]/10 text-[#a9d0f4]"><Icon size={22} aria-hidden="true" /></div><p className="font-display text-3xl italic">{name}</p><p className="mt-2 text-sm text-muted">{detail}</p><p className="mt-6 flex items-center gap-2 text-[10px] uppercase tracking-[.16em] text-[#a9d0f4]"><BadgeCheck size={14} aria-hidden="true" />{tag}</p></article>)}</div></section><section className="border-y border-stroke bg-surface/30 px-6 py-20 md:py-28"><div className="mx-auto max-w-[1100px]"><SectionTitle label="The advantage" title={<>More than a <em className="font-display italic">hackathon.</em></>} text="A practical launchpad built for students and early-stage founders who are ready to move their work forward." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['01', 'Startup mentorship', 'Get direct feedback on the problem, product and pitch.'], ['02', 'Investor exposure', 'Learn what makes an early idea credible to the next room.'], ['03', 'Networking', 'Meet builders, mentors and future collaborators.'], ['04', 'Incentives', '10–15 KTU Points plus duty leave support.']].map(([num, title, body]) => <article key={title} className="rounded-3xl border border-stroke bg-bg p-6"><p className="mb-8 font-display text-3xl italic text-muted">{num}</p><h3 className="mb-2 text-lg">{title}</h3><p className="text-sm leading-relaxed text-muted">{body}</p></article>)}</div></div></section></>;
}

export function TracksAndSchedule() {
  const trackFeatures = [['Problem discovery and validation', 'Prototype and narrative design', 'Team formation support'], ['Product and business-model review', 'Pitch and scale strategy', 'Founder-focused mentorship']];
  return <><section id="tracks" className="mx-auto max-w-[1100px] px-6 py-20 md:py-28"><SectionTitle label="Participant tracks" title={<>Choose your <em className="font-display italic">starting point.</em></>} /><div className="grid gap-5 md:grid-cols-2">{[['Track A', 'The Launchpad', 'For ideators turning a promising campus concept into a focused first venture.', 'rounded-3xl border border-[#89AACC]/40 bg-[#89AACC]/10 p-8'], ['Track B', 'The Refinery', 'For founders with an early prototype who need sharper positioning, proof and momentum.', 'rounded-3xl border border-white/15 bg-surface p-8']].map(([label, title, body, className], index) => <article key={title} className={className}><p className="text-xs uppercase tracking-[.2em] text-muted">{label}</p><h3 className="my-3 font-display text-4xl italic">{title}</h3><p className="mb-7 text-sm text-muted">{body}</p><ul className="space-y-3 text-sm">{trackFeatures[index].map((feature) => <li key={feature} className="flex items-center gap-2"><ArrowRight size={15} aria-hidden="true" />{feature}</li>)}</ul></article>)}</div></section><section id="schedule" className="border-y border-stroke bg-surface/30 px-6 py-20 md:py-28"><div className="mx-auto max-w-[1100px]"><SectionTitle label="Two-day programme" title={<>Build, pitch, <em className="font-display italic">sustain.</em></>} />{[['Day 1', 'Ideate + Validate + Build', 'Frame the problem, test the assumptions and turn your idea into a working direction.'], ['Day 2', 'Pitch + Scale + Sustain', 'Refine your venture story, learn the next moves and present the work.']].map(([day, title, text], index) => <Accordion key={day} label={day} title={title} initiallyOpen={index === 0}>{text}</Accordion>)}</div></section></>;
}

export function MentorSection() {
  return <section className="mx-auto max-w-[1100px] px-6 py-20 md:py-28"><SectionTitle label="Speakers & mentors" title={<>Built for honest <em className="font-display italic">feedback.</em></>} text="The mentor and speaker lineup will be announced shortly. The programme is designed around practical, small-group conversations—not passive sessions." /><div className="grid gap-4 md:grid-cols-3">{[[BadgeCheck, 'Mentor clinics', 'Focused feedback on your problem, product and pitch.'], [Network, 'Founder rooms', 'Build connections with peers who are equally serious about shipping.'], [ArrowUpRight, 'Investor conversations', 'Understand the proof points that make an early venture credible.']].map(([Icon, title, body]) => { const CardIcon = Icon as typeof BadgeCheck; return <article key={title as string} className="group relative overflow-hidden rounded-3xl border border-stroke bg-surface p-7 transition hover:border-[#89AACC]/60"><CardIcon className="mb-12 text-[#a9d0f4] transition group-hover:scale-110" size={27} aria-hidden="true" /><h3 className="font-display text-3xl italic">{title as string}</h3><p className="mt-3 text-sm leading-relaxed text-muted">{body as string}</p><span className="absolute bottom-0 left-0 h-px w-full origin-left scale-x-0 accent-gradient transition group-hover:scale-x-100" /></article> })}</div></section>;
}
export function VenueSponsorsFaq() {
  const partners = [
    ['IEEE Kerala Section', '/sponsors/ieee-kerala-section.png'],
    ['IEEE IA/IE/PELS Joint Chapter Kerala', '/sponsors/ieee-ia-ie-pels.png'],
    ['IEEE Young Professionals', '/sponsors/ieee-young-professionals-horizontal.png?v=20260803'],
    ['Christ College of Engineering', '/sponsors/christ-college-of-engineering.png'],
    ['IEEE Robotics and Automation Society Kerala Section', '/sponsors/ieee-ras-kerala-section.png'],
    ['Srishti Robotics', '/sponsors/srishti-robotics.png'],
    ['CAD Center — Autodesk Authorized Training Center', '/sponsors/cad-center.png'],
  ];

  return <><section id="venue" className="border-y border-stroke bg-surface/30 px-6 py-20 md:py-28"><div className="mx-auto grid max-w-[1100px] gap-10 md:grid-cols-2 md:items-center"><div><SectionTitle label="Venue & logistics" title={<>CCE, <em className="font-display italic">Irinjalakuda.</em></>} text="Christ College of Engineering will host two days of building, critique and venture-focused conversations. Exact reporting details will be shared with registered participants." /><p className="text-sm text-muted">Christ College of Engineering, Irinjalakuda<br />Kerala, India</p></div><div className="group relative min-h-[340px] overflow-hidden rounded-3xl border border-white/15 bg-surface"><img src="/christ-exterior.png" alt="Christ College of Engineering, Irinjalakuda" loading="lazy" className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-transparent" /><a href="https://maps.google.com/?q=Christ%20College%20of%20Engineering%20Irinjalakuda" target="_blank" rel="noreferrer" className="absolute bottom-5 left-5 inline-flex min-h-11 items-center gap-2 rounded-full border border-white/30 bg-black/40 px-4 text-sm text-white backdrop-blur transition hover:bg-black/65">View on Maps <ArrowUpRight size={16} aria-hidden="true" /></a></div></div></section><section id="partners" className="border-y border-stroke bg-surface/30 px-6 py-20"><div className="mx-auto max-w-[1100px]"><SectionTitle label="Sponsors & partners" title={<>The people who make it <em className="font-display italic">possible.</em></>} text="UNFOLD is brought to life by our institutional sponsors and partners." /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{partners.map(([name, src]) => <div key={name} className="grid min-h-32 place-items-center rounded-2xl border border-stroke bg-bg p-6"><img src={src} alt={`${name} logo`} loading="lazy" decoding="async" className="max-h-20 max-w-full object-contain" /></div>)}</div></div></section><section id="faq" className="mx-auto max-w-[900px] px-6 py-20 md:py-28"><SectionTitle label="FAQ" title={<>Questions, <em className="font-display italic">answered.</em></>} />{[['Who is UNFOLD for?', '3rd and 4th year engineering students, B.Tech/M.Tech graduates, and early-stage founders.'], ['Where will UNFOLD take place?', 'At Christ College of Engineering (CCE), Irinjalakuda, on September 12–13, 2026.'], ['How do I register?', 'Select a registration button to open the delegate application form.'], ['Will there be duty leave and KTU points?', 'The event offers 10–15 KTU Points and duty leave support; share the final requirement with your college team.']].map(([question, answer]) => <Accordion key={question} title={question}>{answer}</Accordion>)}</section></>;
}
